spring:
  profiles:
    active: dev
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ihome?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: qweasd0.2
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    mybatis依赖
#mybatis:
#  type-aliases-package: cn.ymcat.ihome.dao
logging:
  config: classpath:logback-spring.xml
level:
  cn.ymcat.ihome: INFO